# Generated by Django 2.1.7 on 2019-05-01 11:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('website', models.CharField(max_length=100)),
                ('cover', models.ImageField(default='all_covers/cover.jpg', upload_to='all_covers/')),
                ('infrastructure', models.IntegerField(default=1)),
                ('placements', models.IntegerField(default=1)),
                ('faculty', models.IntegerField(default=1)),
                ('management', models.IntegerField(default=1)),
                ('summary', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('phone', models.CharField(max_length=10)),
                ('rating', models.IntegerField(default=1)),
                ('qualification', models.CharField(max_length=100)),
                ('designation', models.CharField(max_length=100)),
                ('department', models.CharField(choices=[('CSE', 'Computer Science'), ('ISE', 'Information Science'), ('ECE', 'Electronics and Communication'), ('EEE', 'Electrical and Electronics'), ('ME', 'Mechanical'), ('CE', 'Civil'), ('TC', 'Telecommunication'), ('BT', 'Biotechnology')], max_length=2)),
                ('institute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='review.Institution')),
            ],
        ),
    ]
