# Generated by Django 2.1.7 on 2019-05-01 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='department',
            field=models.CharField(choices=[('Computer Science', 'CSE'), ('Information Science', 'ISE'), ('Electronics and Communication', 'ECE'), ('Electrical and Electronics', 'EEE'), ('Mechanical', 'ME'), ('Civil', 'CE'), ('Telecommunication', 'TC'), ('Biotechnology', 'BT')], max_length=2),
        ),
    ]
