# Generated by Django 2.1.7 on 2019-05-01 11:44

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('review', '0004_auto_20190501_1705'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstitutionFeedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comments', models.CharField(max_length=250)),
                ('timestamp', models.DateTimeField(default=datetime.datetime.now)),
                ('infrastructure', models.IntegerField(default=1)),
                ('placements', models.IntegerField(default=1)),
                ('faculty', models.IntegerField(default=1)),
                ('management', models.IntegerField(default=1)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='review.Institution')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
