# Generated by Django 2.1.7 on 2019-05-01 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0006_teacherfeedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='average_rating',
            field=models.IntegerField(default=1),
        ),
    ]
