# Generated by Django 2.1.7 on 2019-05-01 17:17

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0007_institution_average_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institution',
            name='faculty',
            field=jsonfield.fields.JSONField(default={1: 0, 2: 0, 3: 0, 4: 0, 5: 0}),
        ),
        migrations.AlterField(
            model_name='institution',
            name='infrastructure',
            field=jsonfield.fields.JSONField(default={1: 0, 2: 0, 3: 0, 4: 0, 5: 0}),
        ),
        migrations.AlterField(
            model_name='institution',
            name='management',
            field=jsonfield.fields.JSONField(default={1: 0, 2: 0, 3: 0, 4: 0, 5: 0}),
        ),
        migrations.AlterField(
            model_name='institution',
            name='placements',
            field=jsonfield.fields.JSONField(default={1: 0, 2: 0, 3: 0, 4: 0, 5: 0}),
        ),
    ]
